[2022-07-06 19:45:27,260] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: twitter_dag.load_data_to_cosmosDB manual__2022-07-06T22:09:22.719912+00:00 [queued]>
[2022-07-06 19:45:27,269] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: twitter_dag.load_data_to_cosmosDB manual__2022-07-06T22:09:22.719912+00:00 [queued]>
[2022-07-06 19:45:27,270] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-06 19:45:27,270] {taskinstance.py:1357} INFO - Starting attempt 1 of 4
[2022-07-06 19:45:27,270] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-06 19:45:27,292] {taskinstance.py:1377} INFO - Executing <Task(DatabricksRunNowOperator): load_data_to_cosmosDB> on 2022-07-06 22:09:22.719912+00:00
[2022-07-06 19:45:27,294] {standard_task_runner.py:52} INFO - Started process 111551 to run task
[2022-07-06 19:45:27,301] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'twitter_dag', 'load_data_to_cosmosDB', 'manual__2022-07-06T22:09:22.719912+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/twitter_dag.py', '--cfg-path', '/tmp/tmpb7fjh22l', '--error-file', '/tmp/tmpky7uctbt']
[2022-07-06 19:45:27,302] {standard_task_runner.py:80} INFO - Job 72: Subtask load_data_to_cosmosDB
[2022-07-06 19:45:27,381] {task_command.py:370} INFO - Running <TaskInstance: twitter_dag.load_data_to_cosmosDB manual__2022-07-06T22:09:22.719912+00:00 [running]> on host nicholas-VirtualBox
[2022-07-06 19:45:27,460] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=nicholas.comuni@outlook.com
AIRFLOW_CTX_DAG_OWNER=Nicholas
AIRFLOW_CTX_DAG_ID=twitter_dag
AIRFLOW_CTX_TASK_ID=load_data_to_cosmosDB
AIRFLOW_CTX_EXECUTION_DATE=2022-07-06T22:09:22.719912+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-06T22:09:22.719912+00:00
[2022-07-06 19:45:27,469] {base.py:68} INFO - Using connection ID 'databricks_conn' for task execution.
[2022-07-06 19:45:27,471] {databricks_base.py:406} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2022-07-06 19:45:28,188] {databricks.py:49} INFO - Run submitted with run_id: 21480
[2022-07-06 19:45:28,189] {databricks_base.py:406} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2022-07-06 19:45:28,863] {databricks_base.py:406} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2022-07-06 19:45:29,403] {databricks.py:71} INFO - load_data_to_cosmosDB in run state: {'life_cycle_state': 'RUNNING', 'result_state': '', 'state_message': ''}
[2022-07-06 19:45:29,403] {databricks.py:72} INFO - View run status, Spark UI, and logs at https://adb-770153189229877.17.azuredatabricks.net/?o=770153189229877#job/854986352167304/run/21480
[2022-07-06 19:45:29,403] {databricks.py:73} INFO - Sleeping for 30 seconds.
[2022-07-06 19:45:59,424] {databricks_base.py:406} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2022-07-06 19:46:00,190] {databricks.py:71} INFO - load_data_to_cosmosDB in run state: {'life_cycle_state': 'RUNNING', 'result_state': '', 'state_message': ''}
[2022-07-06 19:46:00,190] {databricks.py:72} INFO - View run status, Spark UI, and logs at https://adb-770153189229877.17.azuredatabricks.net/?o=770153189229877#job/854986352167304/run/21480
[2022-07-06 19:46:00,190] {databricks.py:73} INFO - Sleeping for 30 seconds.
[2022-07-06 19:46:30,221] {databricks_base.py:406} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2022-07-06 19:46:30,799] {databricks.py:71} INFO - load_data_to_cosmosDB in run state: {'life_cycle_state': 'RUNNING', 'result_state': '', 'state_message': ''}
[2022-07-06 19:46:30,799] {databricks.py:72} INFO - View run status, Spark UI, and logs at https://adb-770153189229877.17.azuredatabricks.net/?o=770153189229877#job/854986352167304/run/21480
[2022-07-06 19:46:30,799] {databricks.py:73} INFO - Sleeping for 30 seconds.
[2022-07-06 19:47:00,814] {databricks_base.py:406} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2022-07-06 19:47:01,394] {databricks.py:71} INFO - load_data_to_cosmosDB in run state: {'life_cycle_state': 'RUNNING', 'result_state': '', 'state_message': ''}
[2022-07-06 19:47:01,394] {databricks.py:72} INFO - View run status, Spark UI, and logs at https://adb-770153189229877.17.azuredatabricks.net/?o=770153189229877#job/854986352167304/run/21480
[2022-07-06 19:47:01,394] {databricks.py:73} INFO - Sleeping for 30 seconds.
[2022-07-06 19:47:31,399] {databricks_base.py:406} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2022-07-06 19:47:31,971] {databricks.py:71} INFO - load_data_to_cosmosDB in run state: {'life_cycle_state': 'RUNNING', 'result_state': '', 'state_message': ''}
[2022-07-06 19:47:31,971] {databricks.py:72} INFO - View run status, Spark UI, and logs at https://adb-770153189229877.17.azuredatabricks.net/?o=770153189229877#job/854986352167304/run/21480
[2022-07-06 19:47:31,971] {databricks.py:73} INFO - Sleeping for 30 seconds.
[2022-07-06 19:48:01,991] {databricks_base.py:406} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2022-07-06 19:48:02,653] {databricks_base.py:406} INFO - Using token auth. For security reasons, please set token in Password field instead of extra
[2022-07-06 19:48:03,310] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/databricks/hooks/databricks_base.py", line 498, in _do_api_call
    for attempt in self._get_retry_object():
  File "/home/nicholas/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/nicholas/.local/lib/python3.10/site-packages/tenacity/__init__.py", line 349, in iter
    return fut.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/databricks/hooks/databricks_base.py", line 508, in _do_api_call
    response.raise_for_status()
  File "/home/nicholas/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://adb-770153189229877.17.azuredatabricks.net/api/2.1/jobs/runs/get-output?run_id=21480

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/databricks/operators/databricks.py", line 655, in execute
    _handle_databricks_operator_execution(self, hook, self.log, context)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/databricks/operators/databricks.py", line 63, in _handle_databricks_operator_execution
    run_output = hook.get_run_output(operator.run_id)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/databricks/hooks/databricks.py", line 309, in get_run_output
    run_output = self._do_api_call(OUTPUT_RUNS_JOB_ENDPOINT, json)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/databricks/hooks/databricks_base.py", line 514, in _do_api_call
    raise AirflowException(
airflow.exceptions.AirflowException: Response: b'{"error_code":"INVALID_PARAMETER_VALUE","message":"Retrieving the output of runs with multiple tasks is not supported. Please retrieve the output of each individual task run instead."}', Status Code: 400
[2022-07-06 19:48:03,314] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=twitter_dag, task_id=load_data_to_cosmosDB, execution_date=20220706T220922, start_date=20220706T224527, end_date=20220706T224803
[2022-07-06 19:48:03,329] {standard_task_runner.py:92} ERROR - Failed to execute job 72 for task load_data_to_cosmosDB (Response: b'{"error_code":"INVALID_PARAMETER_VALUE","message":"Retrieving the output of runs with multiple tasks is not supported. Please retrieve the output of each individual task run instead."}', Status Code: 400; 111551)
[2022-07-06 19:48:03,364] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-06 19:48:03,374] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
