[2022-07-05 15:31:16,277] {processor.py:153} INFO - Started process (PID=6736) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:31:16,277] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:31:16,278] {logging_mixin.py:115} INFO - [2022-07-05 15:31:16,278] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:31:17,172] {logging_mixin.py:115} INFO - /tmp/tmpd0br_nj5/covid19.json
[2022-07-05 15:31:17,184] {logging_mixin.py:115} INFO - [2022-07-05 15:31:17,180] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 36, in request_twitter_data
    hook = WasbHook(wasb_conn_id="wasbconn")
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 113, in __init__
    self.blob_service_client = self.get_conn()
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 117, in get_conn
    conn = self.get_connection(self.conn_id)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `wasbconn` isn't defined
[2022-07-05 15:31:17,185] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:31:17,199] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 0.925 seconds
[2022-07-05 15:31:53,569] {processor.py:153} INFO - Started process (PID=6988) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:31:53,571] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:31:53,571] {logging_mixin.py:115} INFO - [2022-07-05 15:31:53,571] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:31:54,466] {logging_mixin.py:115} INFO - /tmp/tmp4zkvs78i/covid19.json
[2022-07-05 15:31:54,479] {logging_mixin.py:115} INFO - [2022-07-05 15:31:54,478] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 36, in request_twitter_data
    hook = WasbHook(wasb_conn_id="wasbconn")
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 113, in __init__
    self.blob_service_client = self.get_conn()
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 117, in get_conn
    conn = self.get_connection(self.conn_id)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `wasbconn` isn't defined
[2022-07-05 15:31:54,480] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:31:54,499] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 0.933 seconds
[2022-07-05 15:32:26,939] {processor.py:153} INFO - Started process (PID=7122) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:32:26,939] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:32:26,940] {logging_mixin.py:115} INFO - [2022-07-05 15:32:26,940] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:32:27,787] {logging_mixin.py:115} INFO - /tmp/tmpzbjgt9pz/covid19.json
[2022-07-05 15:32:27,804] {logging_mixin.py:115} INFO - [2022-07-05 15:32:27,803] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 36, in request_twitter_data
    hook = WasbHook(wasb_conn_id="wasbconn")
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 113, in __init__
    self.blob_service_client = self.get_conn()
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 117, in get_conn
    conn = self.get_connection(self.conn_id)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `wasbconn` isn't defined
[2022-07-05 15:32:27,805] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:32:27,826] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 0.889 seconds
[2022-07-05 15:33:01,748] {processor.py:153} INFO - Started process (PID=7348) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:33:01,749] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:33:01,749] {logging_mixin.py:115} INFO - [2022-07-05 15:33:01,749] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:33:02,564] {logging_mixin.py:115} INFO - /tmp/tmp7swe01hi/covid19.json
[2022-07-05 15:33:02,572] {logging_mixin.py:115} INFO - [2022-07-05 15:33:02,572] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:33:02,574] {logging_mixin.py:115} INFO - [2022-07-05 15:33:02,573] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 255, in load_file
    with open(file_path, 'rb') as data:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp7swe01hi/covid19.json'
[2022-07-05 15:33:02,575] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:33:02,590] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 0.845 seconds
[2022-07-05 15:33:35,483] {processor.py:153} INFO - Started process (PID=7413) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:33:35,484] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:33:35,484] {logging_mixin.py:115} INFO - [2022-07-05 15:33:35,484] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:33:36,360] {logging_mixin.py:115} INFO - /tmp/tmp5i1me3vk/covid19.json
[2022-07-05 15:33:36,381] {logging_mixin.py:115} INFO - [2022-07-05 15:33:36,381] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:33:36,383] {logging_mixin.py:115} INFO - [2022-07-05 15:33:36,382] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 255, in load_file
    with open(file_path, 'rb') as data:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp5i1me3vk/covid19.json'
[2022-07-05 15:33:36,384] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:33:36,411] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 0.930 seconds
[2022-07-05 15:34:09,195] {processor.py:153} INFO - Started process (PID=7480) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:34:09,196] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:34:09,197] {logging_mixin.py:115} INFO - [2022-07-05 15:34:09,197] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:34:09,969] {logging_mixin.py:115} INFO - /tmp/tmpxbs555lr/covid19.json
[2022-07-05 15:34:09,977] {logging_mixin.py:115} INFO - [2022-07-05 15:34:09,977] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:34:09,978] {logging_mixin.py:115} INFO - [2022-07-05 15:34:09,977] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 255, in load_file
    with open(file_path, 'rb') as data:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxbs555lr/covid19.json'
[2022-07-05 15:34:09,979] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:34:09,993] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 0.800 seconds
[2022-07-05 15:34:42,641] {processor.py:153} INFO - Started process (PID=7605) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:34:42,641] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:34:42,641] {logging_mixin.py:115} INFO - [2022-07-05 15:34:42,641] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:34:43,406] {logging_mixin.py:115} INFO - /tmp/tmp5zcyjv1_/covid19.json
[2022-07-05 15:34:43,414] {logging_mixin.py:115} INFO - [2022-07-05 15:34:43,414] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:34:43,415] {logging_mixin.py:115} INFO - [2022-07-05 15:34:43,415] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 255, in load_file
    with open(file_path, 'rb') as data:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp5zcyjv1_/covid19.json'
[2022-07-05 15:34:43,417] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:34:43,431] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 0.792 seconds
[2022-07-05 15:35:15,535] {processor.py:153} INFO - Started process (PID=7677) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:35:15,538] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:35:15,538] {logging_mixin.py:115} INFO - [2022-07-05 15:35:15,538] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:35:16,324] {logging_mixin.py:115} INFO - /tmp/tmpfk0vqpri/covid19.json
[2022-07-05 15:35:16,332] {logging_mixin.py:115} INFO - [2022-07-05 15:35:16,332] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:35:16,333] {logging_mixin.py:115} INFO - [2022-07-05 15:35:16,333] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 255, in load_file
    with open(file_path, 'rb') as data:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpfk0vqpri/covid19.json'
[2022-07-05 15:35:16,335] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:35:16,348] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 0.815 seconds
[2022-07-05 15:35:48,568] {processor.py:153} INFO - Started process (PID=7846) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:35:48,568] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:35:48,569] {logging_mixin.py:115} INFO - [2022-07-05 15:35:48,569] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:35:49,339] {logging_mixin.py:115} INFO - /tmp/tmp1yra37m1/covid19.json
[2022-07-05 15:35:49,348] {logging_mixin.py:115} INFO - [2022-07-05 15:35:49,348] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:35:49,427] {logging_mixin.py:115} INFO - [2022-07-05 15:35:49,427] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2816'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '4aa29e84-fc91-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:35:50,415] {logging_mixin.py:115} INFO - [2022-07-05 15:35:50,415] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:35:52 GMT'
    'ETag': '"0x8DA5EB53067B9E1"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '837a8f05-c01e-0048-4e9e-905630000000'
    'x-ms-client-request-id': '4aa29e84-fc91-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:35:51 GMT'
[2022-07-05 15:35:50,421] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:35:50,475] {logging_mixin.py:115} INFO - [2022-07-05 15:35:50,475] {manager.py:508} INFO - Created Permission View: can edit on DAG:twitter_dag2
[2022-07-05 15:35:50,488] {logging_mixin.py:115} INFO - [2022-07-05 15:35:50,488] {manager.py:508} INFO - Created Permission View: can read on DAG:twitter_dag2
[2022-07-05 15:35:50,497] {logging_mixin.py:115} INFO - [2022-07-05 15:35:50,497] {manager.py:508} INFO - Created Permission View: can delete on DAG:twitter_dag2
[2022-07-05 15:35:50,497] {logging_mixin.py:115} INFO - [2022-07-05 15:35:50,497] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:35:50,505] {logging_mixin.py:115} INFO - [2022-07-05 15:35:50,505] {dag.py:2398} INFO - Creating ORM DAG for twitter_dag2
[2022-07-05 15:35:50,518] {logging_mixin.py:115} INFO - [2022-07-05 15:35:50,518] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-01T00:00:00+00:00, run_after=2022-05-02T00:00:00+00:00
[2022-07-05 15:35:50,545] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.979 seconds
[2022-07-05 15:36:23,977] {processor.py:153} INFO - Started process (PID=7955) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:36:23,977] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:36:23,978] {logging_mixin.py:115} INFO - [2022-07-05 15:36:23,978] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:36:24,809] {logging_mixin.py:115} INFO - /tmp/tmpelc3hkak/covid19.json
[2022-07-05 15:36:24,816] {logging_mixin.py:115} INFO - [2022-07-05 15:36:24,816] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:36:24,818] {logging_mixin.py:115} INFO - [2022-07-05 15:36:24,818] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2849'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5fbad7dc-fc91-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:36:25,464] {logging_mixin.py:115} INFO - [2022-07-05 15:36:25,464] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '44c09ff6-a01e-0003-5e9e-90aa63000000'
    'x-ms-client-request-id': '5fbad7dc-fc91-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:36:26 GMT'
[2022-07-05 15:36:25,476] {logging_mixin.py:115} INFO - [2022-07-05 15:36:25,466] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:44c09ff6-a01e-0003-5e9e-90aa63000000
Time:2022-07-05T18:36:27.0913420Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:44c09ff6-a01e-0003-5e9e-90aa63000000
Time:2022-07-05T18:36:27.0913420Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:44c09ff6-a01e-0003-5e9e-90aa63000000
Time:2022-07-05T18:36:27.0913420Z</Message></Error>
[2022-07-05 15:36:25,477] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:36:25,489] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.515 seconds
[2022-07-05 15:37:00,999] {processor.py:153} INFO - Started process (PID=8033) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:37:01,000] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:37:01,000] {logging_mixin.py:115} INFO - [2022-07-05 15:37:01,000] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:37:01,804] {logging_mixin.py:115} INFO - /tmp/tmpo96_5h25/covid19.json
[2022-07-05 15:37:01,811] {logging_mixin.py:115} INFO - [2022-07-05 15:37:01,810] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:37:01,833] {logging_mixin.py:115} INFO - [2022-07-05 15:37:01,833] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '3421'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '75c89370-fc91-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:37:02,773] {logging_mixin.py:115} INFO - [2022-07-05 15:37:02,773] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'cdcd5fff-301e-003e-209e-90dc78000000'
    'x-ms-client-request-id': '75c89370-fc91-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:37:04 GMT'
[2022-07-05 15:37:02,776] {logging_mixin.py:115} INFO - [2022-07-05 15:37:02,774] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:cdcd5fff-301e-003e-209e-90dc78000000
Time:2022-07-05T18:37:04.3824693Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:cdcd5fff-301e-003e-209e-90dc78000000
Time:2022-07-05T18:37:04.3824693Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:cdcd5fff-301e-003e-209e-90dc78000000
Time:2022-07-05T18:37:04.3824693Z</Message></Error>
[2022-07-05 15:37:02,777] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:37:02,791] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.794 seconds
[2022-07-05 15:37:36,456] {processor.py:153} INFO - Started process (PID=8107) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:37:36,456] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:37:36,456] {logging_mixin.py:115} INFO - [2022-07-05 15:37:36,456] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:37:37,271] {logging_mixin.py:115} INFO - /tmp/tmpfs4lmj7q/covid19.json
[2022-07-05 15:37:37,278] {logging_mixin.py:115} INFO - [2022-07-05 15:37:37,278] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:37:37,280] {logging_mixin.py:115} INFO - [2022-07-05 15:37:37,279] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '3480'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8aeb9afe-fc91-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:37:37,945] {logging_mixin.py:115} INFO - [2022-07-05 15:37:37,945] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9535c6cf-701e-0062-7b9e-908920000000'
    'x-ms-client-request-id': '8aeb9afe-fc91-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:37:38 GMT'
[2022-07-05 15:37:37,948] {logging_mixin.py:115} INFO - [2022-07-05 15:37:37,946] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:9535c6cf-701e-0062-7b9e-908920000000
Time:2022-07-05T18:37:39.5353941Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:9535c6cf-701e-0062-7b9e-908920000000
Time:2022-07-05T18:37:39.5353941Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:9535c6cf-701e-0062-7b9e-908920000000
Time:2022-07-05T18:37:39.5353941Z</Message></Error>
[2022-07-05 15:37:37,948] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:37:37,967] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.513 seconds
[2022-07-05 15:38:10,943] {processor.py:153} INFO - Started process (PID=8181) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:38:10,943] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:38:10,944] {logging_mixin.py:115} INFO - [2022-07-05 15:38:10,944] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:38:11,732] {logging_mixin.py:115} INFO - /tmp/tmpjh8u237o/covid19.json
[2022-07-05 15:38:11,739] {logging_mixin.py:115} INFO - [2022-07-05 15:38:11,739] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:38:11,741] {logging_mixin.py:115} INFO - [2022-07-05 15:38:11,741] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2649'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '9f75efe2-fc91-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:38:12,694] {logging_mixin.py:115} INFO - [2022-07-05 15:38:12,694] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '827e5876-801e-0082-569e-900ab9000000'
    'x-ms-client-request-id': '9f75efe2-fc91-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:38:14 GMT'
[2022-07-05 15:38:12,697] {logging_mixin.py:115} INFO - [2022-07-05 15:38:12,695] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:827e5876-801e-0082-569e-900ab9000000
Time:2022-07-05T18:38:14.2650100Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:827e5876-801e-0082-569e-900ab9000000
Time:2022-07-05T18:38:14.2650100Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:827e5876-801e-0082-569e-900ab9000000
Time:2022-07-05T18:38:14.2650100Z</Message></Error>
[2022-07-05 15:38:12,698] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:38:12,734] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.793 seconds
[2022-07-05 15:38:46,963] {processor.py:153} INFO - Started process (PID=8256) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:38:46,963] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:38:46,963] {logging_mixin.py:115} INFO - [2022-07-05 15:38:46,963] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:38:47,797] {logging_mixin.py:115} INFO - /tmp/tmptmxckc6v/covid19.json
[2022-07-05 15:38:47,804] {logging_mixin.py:115} INFO - [2022-07-05 15:38:47,804] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:38:47,806] {logging_mixin.py:115} INFO - [2022-07-05 15:38:47,806] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2912'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b4f50a42-fc91-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:38:48,459] {logging_mixin.py:115} INFO - [2022-07-05 15:38:48,459] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd526c60c-901e-0045-3e9e-909ee4000000'
    'x-ms-client-request-id': 'b4f50a42-fc91-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:38:49 GMT'
[2022-07-05 15:38:48,462] {logging_mixin.py:115} INFO - [2022-07-05 15:38:48,460] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:d526c60c-901e-0045-3e9e-909ee4000000
Time:2022-07-05T18:38:50.0152054Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:d526c60c-901e-0045-3e9e-909ee4000000
Time:2022-07-05T18:38:50.0152054Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:d526c60c-901e-0045-3e9e-909ee4000000
Time:2022-07-05T18:38:50.0152054Z</Message></Error>
[2022-07-05 15:38:48,462] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:38:48,479] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.519 seconds
[2022-07-05 15:39:19,007] {processor.py:153} INFO - Started process (PID=8317) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:39:19,007] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:39:19,008] {logging_mixin.py:115} INFO - [2022-07-05 15:39:19,008] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:39:19,825] {logging_mixin.py:115} INFO - /tmp/tmpix61h_c6/covid19.json
[2022-07-05 15:39:19,831] {logging_mixin.py:115} INFO - [2022-07-05 15:39:19,831] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:39:19,833] {logging_mixin.py:115} INFO - [2022-07-05 15:39:19,833] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '3043'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c80bfeb0-fc91-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:39:20,760] {logging_mixin.py:115} INFO - [2022-07-05 15:39:20,759] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2d98a247-601e-0023-629e-90d1c4000000'
    'x-ms-client-request-id': 'c80bfeb0-fc91-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:39:21 GMT'
[2022-07-05 15:39:20,763] {logging_mixin.py:115} INFO - [2022-07-05 15:39:20,760] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:2d98a247-601e-0023-629e-90d1c4000000
Time:2022-07-05T18:39:22.2973497Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:2d98a247-601e-0023-629e-90d1c4000000
Time:2022-07-05T18:39:22.2973497Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:2d98a247-601e-0023-629e-90d1c4000000
Time:2022-07-05T18:39:22.2973497Z</Message></Error>
[2022-07-05 15:39:20,763] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:39:20,778] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.774 seconds
[2022-07-05 15:39:53,861] {processor.py:153} INFO - Started process (PID=8387) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:39:53,863] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:39:53,863] {logging_mixin.py:115} INFO - [2022-07-05 15:39:53,863] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:39:54,688] {logging_mixin.py:115} INFO - /tmp/tmpd4_qts6j/covid19.json
[2022-07-05 15:39:54,696] {logging_mixin.py:115} INFO - [2022-07-05 15:39:54,696] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:39:54,698] {logging_mixin.py:115} INFO - [2022-07-05 15:39:54,698] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2746'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'dcd3f1ea-fc91-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:39:55,347] {logging_mixin.py:115} INFO - [2022-07-05 15:39:55,347] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd1003fa5-a01e-0095-0a9e-90a3b2000000'
    'x-ms-client-request-id': 'dcd3f1ea-fc91-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:39:56 GMT'
[2022-07-05 15:39:55,350] {logging_mixin.py:115} INFO - [2022-07-05 15:39:55,348] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:d1003fa5-a01e-0095-0a9e-90a3b2000000
Time:2022-07-05T18:39:56.8726816Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:d1003fa5-a01e-0095-0a9e-90a3b2000000
Time:2022-07-05T18:39:56.8726816Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:d1003fa5-a01e-0095-0a9e-90a3b2000000
Time:2022-07-05T18:39:56.8726816Z</Message></Error>
[2022-07-05 15:39:55,351] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:39:55,366] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.506 seconds
[2022-07-05 15:40:31,147] {processor.py:153} INFO - Started process (PID=8460) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:40:31,148] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:40:31,148] {logging_mixin.py:115} INFO - [2022-07-05 15:40:31,148] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:40:31,958] {logging_mixin.py:115} INFO - /tmp/tmpx36pdadj/covid19.json
[2022-07-05 15:40:31,966] {logging_mixin.py:115} INFO - [2022-07-05 15:40:31,966] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:40:31,968] {logging_mixin.py:115} INFO - [2022-07-05 15:40:31,968] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2682'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f30ae63a-fc91-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:40:32,786] {logging_mixin.py:115} INFO - [2022-07-05 15:40:32,786] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'bdee50ec-501e-0065-539e-90e543000000'
    'x-ms-client-request-id': 'f30ae63a-fc91-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:40:33 GMT'
[2022-07-05 15:40:32,789] {logging_mixin.py:115} INFO - [2022-07-05 15:40:32,787] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:bdee50ec-501e-0065-539e-90e543000000
Time:2022-07-05T18:40:34.2915772Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:bdee50ec-501e-0065-539e-90e543000000
Time:2022-07-05T18:40:34.2915772Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:bdee50ec-501e-0065-539e-90e543000000
Time:2022-07-05T18:40:34.2915772Z</Message></Error>
[2022-07-05 15:40:32,790] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:40:32,806] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.661 seconds
[2022-07-05 15:41:03,037] {processor.py:153} INFO - Started process (PID=8595) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:41:03,038] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:41:03,038] {logging_mixin.py:115} INFO - [2022-07-05 15:41:03,038] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:41:03,829] {logging_mixin.py:115} INFO - /tmp/tmp0uk4q1ug/covid19.json
[2022-07-05 15:41:03,836] {logging_mixin.py:115} INFO - [2022-07-05 15:41:03,836] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:41:03,838] {logging_mixin.py:115} INFO - [2022-07-05 15:41:03,838] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2612'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0609db7e-fc92-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:41:04,477] {logging_mixin.py:115} INFO - [2022-07-05 15:41:04,477] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f10fd358-001e-008c-079e-902309000000'
    'x-ms-client-request-id': '0609db7e-fc92-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:41:05 GMT'
[2022-07-05 15:41:04,480] {logging_mixin.py:115} INFO - [2022-07-05 15:41:04,478] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:f10fd358-001e-008c-079e-902309000000
Time:2022-07-05T18:41:05.9679773Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:f10fd358-001e-008c-079e-902309000000
Time:2022-07-05T18:41:05.9679773Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:f10fd358-001e-008c-079e-902309000000
Time:2022-07-05T18:41:05.9679773Z</Message></Error>
[2022-07-05 15:41:04,480] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:41:04,507] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.472 seconds
[2022-07-05 15:41:38,605] {processor.py:153} INFO - Started process (PID=8690) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:41:38,606] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:41:38,606] {logging_mixin.py:115} INFO - [2022-07-05 15:41:38,606] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:41:39,411] {logging_mixin.py:115} INFO - /tmp/tmpkh38ibep/covid19.json
[2022-07-05 15:41:39,418] {logging_mixin.py:115} INFO - [2022-07-05 15:41:39,418] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:41:39,420] {logging_mixin.py:115} INFO - [2022-07-05 15:41:39,420] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2743'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '1b3f4ace-fc92-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:41:40,348] {logging_mixin.py:115} INFO - [2022-07-05 15:41:40,348] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8d2558ef-201e-00a4-139e-9042a1000000'
    'x-ms-client-request-id': '1b3f4ace-fc92-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:41:41 GMT'
[2022-07-05 15:41:40,351] {logging_mixin.py:115} INFO - [2022-07-05 15:41:40,349] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:8d2558ef-201e-00a4-139e-9042a1000000
Time:2022-07-05T18:41:41.8236636Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:8d2558ef-201e-00a4-139e-9042a1000000
Time:2022-07-05T18:41:41.8236636Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:8d2558ef-201e-00a4-139e-9042a1000000
Time:2022-07-05T18:41:41.8236636Z</Message></Error>
[2022-07-05 15:41:40,351] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:41:40,364] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.762 seconds
[2022-07-05 15:42:11,229] {processor.py:153} INFO - Started process (PID=8751) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:42:11,230] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:42:11,230] {logging_mixin.py:115} INFO - [2022-07-05 15:42:11,230] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:42:12,026] {logging_mixin.py:115} INFO - /tmp/tmpn1do1w9h/covid19.json
[2022-07-05 15:42:12,034] {logging_mixin.py:115} INFO - [2022-07-05 15:42:12,033] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:42:12,035] {logging_mixin.py:115} INFO - [2022-07-05 15:42:12,035] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '3284'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2eaff6d0-fc92-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:42:12,677] {logging_mixin.py:115} INFO - [2022-07-05 15:42:12,677] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'c653a77e-301e-004c-289e-90db37000000'
    'x-ms-client-request-id': '2eaff6d0-fc92-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:42:13 GMT'
[2022-07-05 15:42:12,681] {logging_mixin.py:115} INFO - [2022-07-05 15:42:12,678] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:c653a77e-301e-004c-289e-90db37000000
Time:2022-07-05T18:42:14.1347031Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:c653a77e-301e-004c-289e-90db37000000
Time:2022-07-05T18:42:14.1347031Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:c653a77e-301e-004c-289e-90db37000000
Time:2022-07-05T18:42:14.1347031Z</Message></Error>
[2022-07-05 15:42:12,681] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:42:12,702] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.475 seconds
[2022-07-05 15:42:47,303] {processor.py:153} INFO - Started process (PID=8929) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:42:47,304] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:42:47,304] {logging_mixin.py:115} INFO - [2022-07-05 15:42:47,304] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:42:48,133] {logging_mixin.py:115} INFO - /tmp/tmp5wi24y7r/covid19.json
[2022-07-05 15:42:48,142] {logging_mixin.py:115} INFO - [2022-07-05 15:42:48,142] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:42:48,143] {logging_mixin.py:115} INFO - [2022-07-05 15:42:48,143] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '3466'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '44359eba-fc92-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:42:49,123] {logging_mixin.py:115} INFO - [2022-07-05 15:42:49,123] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '56c17050-701e-003f-439f-9083a4000000'
    'x-ms-client-request-id': '44359eba-fc92-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:42:49 GMT'
[2022-07-05 15:42:49,126] {logging_mixin.py:115} INFO - [2022-07-05 15:42:49,124] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:56c17050-701e-003f-439f-9083a4000000
Time:2022-07-05T18:42:50.5616463Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:56c17050-701e-003f-439f-9083a4000000
Time:2022-07-05T18:42:50.5616463Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:56c17050-701e-003f-439f-9083a4000000
Time:2022-07-05T18:42:50.5616463Z</Message></Error>
[2022-07-05 15:42:49,126] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:42:49,139] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.839 seconds
[2022-07-05 15:43:22,056] {processor.py:153} INFO - Started process (PID=9286) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:43:22,056] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:43:22,057] {logging_mixin.py:115} INFO - [2022-07-05 15:43:22,057] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:43:23,010] {logging_mixin.py:115} INFO - /tmp/tmpjn8ty9sp/covid19.json
[2022-07-05 15:43:23,018] {logging_mixin.py:115} INFO - [2022-07-05 15:43:23,018] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:43:23,019] {logging_mixin.py:115} INFO - [2022-07-05 15:43:23,019] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '3154'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '58ff42a6-fc92-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:43:23,683] {logging_mixin.py:115} INFO - [2022-07-05 15:43:23,683] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '01f07ac3-301e-00a8-2e9f-90d5a9000000'
    'x-ms-client-request-id': '58ff42a6-fc92-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:43:24 GMT'
[2022-07-05 15:43:23,686] {logging_mixin.py:115} INFO - [2022-07-05 15:43:23,684] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:01f07ac3-301e-00a8-2e9f-90d5a9000000
Time:2022-07-05T18:43:25.1106150Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:01f07ac3-301e-00a8-2e9f-90d5a9000000
Time:2022-07-05T18:43:25.1106150Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:01f07ac3-301e-00a8-2e9f-90d5a9000000
Time:2022-07-05T18:43:25.1106150Z</Message></Error>
[2022-07-05 15:43:23,686] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:43:23,711] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.658 seconds
[2022-07-05 15:43:59,201] {processor.py:153} INFO - Started process (PID=9478) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:43:59,202] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:43:59,203] {logging_mixin.py:115} INFO - [2022-07-05 15:43:59,202] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:44:00,119] {logging_mixin.py:115} INFO - /tmp/tmp1z265fin/covid19.json
[2022-07-05 15:44:00,130] {logging_mixin.py:115} INFO - [2022-07-05 15:44:00,130] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:44:00,132] {logging_mixin.py:115} INFO - [2022-07-05 15:44:00,132] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2905'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '6f1e31b4-fc92-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:44:01,081] {logging_mixin.py:115} INFO - [2022-07-05 15:44:01,081] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '506b6afe-901e-009e-5f9f-9058d9000000'
    'x-ms-client-request-id': '6f1e31b4-fc92-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:44:01 GMT'
[2022-07-05 15:44:01,085] {logging_mixin.py:115} INFO - [2022-07-05 15:44:01,082] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:506b6afe-901e-009e-5f9f-9058d9000000
Time:2022-07-05T18:44:02.4804391Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:506b6afe-901e-009e-5f9f-9058d9000000
Time:2022-07-05T18:44:02.4804391Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:506b6afe-901e-009e-5f9f-9058d9000000
Time:2022-07-05T18:44:02.4804391Z</Message></Error>
[2022-07-05 15:44:01,086] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:44:01,104] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.905 seconds
[2022-07-05 15:44:35,323] {processor.py:153} INFO - Started process (PID=9556) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:44:35,323] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:44:35,324] {logging_mixin.py:115} INFO - [2022-07-05 15:44:35,324] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:44:36,143] {logging_mixin.py:115} INFO - /tmp/tmp5ttujh2s/covid19.json
[2022-07-05 15:44:36,150] {logging_mixin.py:115} INFO - [2022-07-05 15:44:36,150] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:44:36,152] {logging_mixin.py:115} INFO - [2022-07-05 15:44:36,152] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '3677'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '84967a6a-fc92-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:44:36,807] {logging_mixin.py:115} INFO - [2022-07-05 15:44:36,807] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '8411781d-f01e-007c-289f-9065f8000000'
    'x-ms-client-request-id': '84967a6a-fc92-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:44:37 GMT'
[2022-07-05 15:44:36,810] {logging_mixin.py:115} INFO - [2022-07-05 15:44:36,808] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:8411781d-f01e-007c-289f-9065f8000000
Time:2022-07-05T18:44:38.1946772Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:8411781d-f01e-007c-289f-9065f8000000
Time:2022-07-05T18:44:38.1946772Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:8411781d-f01e-007c-289f-9065f8000000
Time:2022-07-05T18:44:38.1946772Z</Message></Error>
[2022-07-05 15:44:36,810] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:44:36,828] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.507 seconds
[2022-07-05 15:45:10,301] {processor.py:153} INFO - Started process (PID=9622) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:45:10,301] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:45:10,302] {logging_mixin.py:115} INFO - [2022-07-05 15:45:10,302] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:45:11,189] {logging_mixin.py:115} INFO - /tmp/tmpa94zq31r/covid19.json
[2022-07-05 15:45:11,202] {logging_mixin.py:115} INFO - [2022-07-05 15:45:11,202] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:45:11,205] {logging_mixin.py:115} INFO - [2022-07-05 15:45:11,205] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2861'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '997b0c0c-fc92-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:45:12,058] {logging_mixin.py:115} INFO - [2022-07-05 15:45:12,058] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'bc1ae126-901e-0008-529f-905108000000'
    'x-ms-client-request-id': '997b0c0c-fc92-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:45:12 GMT'
[2022-07-05 15:45:12,061] {logging_mixin.py:115} INFO - [2022-07-05 15:45:12,059] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:bc1ae126-901e-0008-529f-905108000000
Time:2022-07-05T18:45:13.4276082Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:bc1ae126-901e-0008-529f-905108000000
Time:2022-07-05T18:45:13.4276082Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:bc1ae126-901e-0008-529f-905108000000
Time:2022-07-05T18:45:13.4276082Z</Message></Error>
[2022-07-05 15:45:12,062] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:45:12,089] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.794 seconds
[2022-07-05 15:45:43,726] {processor.py:153} INFO - Started process (PID=9692) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:45:43,727] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:45:43,727] {logging_mixin.py:115} INFO - [2022-07-05 15:45:43,727] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:45:44,525] {logging_mixin.py:115} INFO - /tmp/tmp3pz8hb9n/covid19.json
[2022-07-05 15:45:44,534] {logging_mixin.py:115} INFO - [2022-07-05 15:45:44,534] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:45:44,535] {logging_mixin.py:115} INFO - [2022-07-05 15:45:44,535] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2941'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ad58ee60-fc92-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:45:45,201] {logging_mixin.py:115} INFO - [2022-07-05 15:45:45,201] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'bc6e6912-901e-0027-5c9f-905cc3000000'
    'x-ms-client-request-id': 'ad58ee60-fc92-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:45:45 GMT'
[2022-07-05 15:45:45,204] {logging_mixin.py:115} INFO - [2022-07-05 15:45:45,202] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:bc6e6912-901e-0027-5c9f-905cc3000000
Time:2022-07-05T18:45:46.5556494Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:bc6e6912-901e-0027-5c9f-905cc3000000
Time:2022-07-05T18:45:46.5556494Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:bc6e6912-901e-0027-5c9f-905cc3000000
Time:2022-07-05T18:45:46.5556494Z</Message></Error>
[2022-07-05 15:45:45,204] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:45:45,223] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.499 seconds
[2022-07-05 15:46:17,824] {processor.py:153} INFO - Started process (PID=9758) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:46:17,825] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:46:17,825] {logging_mixin.py:115} INFO - [2022-07-05 15:46:17,825] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:46:18,682] {logging_mixin.py:115} INFO - /tmp/tmpmt0ssd6s/covid19.json
[2022-07-05 15:46:18,690] {logging_mixin.py:115} INFO - [2022-07-05 15:46:18,690] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:46:18,692] {logging_mixin.py:115} INFO - [2022-07-05 15:46:18,692] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2786'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'c1b4cb54-fc92-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:46:19,630] {logging_mixin.py:115} INFO - [2022-07-05 15:46:19,630] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'ce2dfa1d-101e-0016-289f-90bdd0000000'
    'x-ms-client-request-id': 'c1b4cb54-fc92-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:46:20 GMT'
[2022-07-05 15:46:19,633] {logging_mixin.py:115} INFO - [2022-07-05 15:46:19,631] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:ce2dfa1d-101e-0016-289f-90bdd0000000
Time:2022-07-05T18:46:20.9668287Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:ce2dfa1d-101e-0016-289f-90bdd0000000
Time:2022-07-05T18:46:20.9668287Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:ce2dfa1d-101e-0016-289f-90bdd0000000
Time:2022-07-05T18:46:20.9668287Z</Message></Error>
[2022-07-05 15:46:19,634] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:46:19,650] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.829 seconds
[2022-07-05 15:46:52,774] {processor.py:153} INFO - Started process (PID=9831) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:46:52,774] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:46:52,774] {logging_mixin.py:115} INFO - [2022-07-05 15:46:52,774] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:46:53,598] {logging_mixin.py:115} INFO - /tmp/tmp3omhjedr/covid19.json
[2022-07-05 15:46:53,606] {logging_mixin.py:115} INFO - [2022-07-05 15:46:53,606] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:46:53,608] {logging_mixin.py:115} INFO - [2022-07-05 15:46:53,608] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/teste'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '3731'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd68498fc-fc92-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:46:54,258] {logging_mixin.py:115} INFO - [2022-07-05 15:46:54,258] {_universal.py:504} INFO - Response status: 409
Response headers:
    'Content-Length': '220'
    'Content-Type': 'application/xml'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '83802f49-c01e-0048-6f9f-905630000000'
    'x-ms-client-request-id': 'd68498fc-fc92-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-error-code': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:46:55 GMT'
[2022-07-05 15:46:54,261] {logging_mixin.py:115} INFO - [2022-07-05 15:46:54,259] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: Operation returned an invalid status 'The specified blob already exists.'
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:83802f49-c01e-0048-6f9f-905630000000
Time:2022-07-05T18:46:55.5776116Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 5, in <module>
    from transformation import *
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 39, in <module>
    request_twitter_data()
  File "/home/nicholas/Desktop/Code/airflow/dags/transformation.py", line 37, in request_twitter_data
    hook.load_file(tmpfile_path, container_name="landingzone",blob_name=filename)
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 256, in load_file
    self.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 341, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_blob_client.py", line 693, in upload_blob
    return upload_block_blob(**options)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 249, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 228, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/nicholas/.local/lib/python3.10/site-packages/azure/core/exceptions.py", line 107, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:83802f49-c01e-0048-6f9f-905630000000
Time:2022-07-05T18:46:55.5776116Z
ErrorCode:BlobAlreadyExists
Error:None
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:83802f49-c01e-0048-6f9f-905630000000
Time:2022-07-05T18:46:55.5776116Z</Message></Error>
[2022-07-05 15:46:54,262] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:46:54,289] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.518 seconds
[2022-07-05 15:47:29,005] {processor.py:153} INFO - Started process (PID=10046) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:47:29,005] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:47:29,006] {logging_mixin.py:115} INFO - [2022-07-05 15:47:29,006] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:47:29,861] {logging_mixin.py:115} INFO - /tmp/tmpl8q7xbtl/covid19.json
[2022-07-05 15:47:29,869] {logging_mixin.py:115} INFO - [2022-07-05 15:47:29,869] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:47:29,871] {logging_mixin.py:115} INFO - [2022-07-05 15:47:29,870] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A47%3A29.861493.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '3017'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'ec21d044-fc92-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:47:30,875] {logging_mixin.py:115} INFO - [2022-07-05 15:47:30,875] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:47:32 GMT'
    'ETag': '"0x8DA5EB6D1B56F8B"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '26797baf-301e-002e-3f9f-901910000000'
    'x-ms-client-request-id': 'ec21d044-fc92-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:47:31 GMT'
[2022-07-05 15:47:30,881] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:47:30,897] {logging_mixin.py:115} INFO - [2022-07-05 15:47:30,897] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:47:30,919] {logging_mixin.py:115} INFO - [2022-07-05 15:47:30,919] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-01T00:00:00+00:00, run_after=2022-05-02T00:00:00+00:00
[2022-07-05 15:47:30,939] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.936 seconds
[2022-07-05 15:47:49,573] {processor.py:153} INFO - Started process (PID=10256) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:47:49,573] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:47:49,573] {logging_mixin.py:115} INFO - [2022-07-05 15:47:49,573] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:47:50,620] {logging_mixin.py:115} INFO - /tmp/tmpf0wpoklt/covid19.json
[2022-07-05 15:47:50,639] {logging_mixin.py:115} INFO - [2022-07-05 15:47:50,638] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:47:50,641] {logging_mixin.py:115} INFO - [2022-07-05 15:47:50,641] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A47%3A50.620536.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2853'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'f8831848-fc92-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:47:51,430] {logging_mixin.py:115} INFO - [2022-07-05 15:47:51,429] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:47:52 GMT'
    'ETag': '"0x8DA5EB6DDF4485A"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '79cb4c76-701e-004d-4f9f-9084eb000000'
    'x-ms-client-request-id': 'f8831848-fc92-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:47:52 GMT'
[2022-07-05 15:47:51,447] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:47:51,471] {logging_mixin.py:115} INFO - [2022-07-05 15:47:51,471] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:47:51,520] {logging_mixin.py:115} INFO - [2022-07-05 15:47:51,520] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-01T00:00:00+00:00, run_after=2022-05-02T00:00:00+00:00
[2022-07-05 15:47:51,555] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.989 seconds
[2022-07-05 15:48:28,161] {processor.py:153} INFO - Started process (PID=10540) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:48:28,162] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:48:28,163] {logging_mixin.py:115} INFO - [2022-07-05 15:48:28,163] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:48:28,971] {logging_mixin.py:115} INFO - /tmp/tmpo12sapso/covid19.json
[2022-07-05 15:48:28,980] {logging_mixin.py:115} INFO - [2022-07-05 15:48:28,980] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:48:28,982] {logging_mixin.py:115} INFO - [2022-07-05 15:48:28,982] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A48%3A28.971220.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2627'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '0f5d877e-fc93-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:48:29,656] {logging_mixin.py:115} INFO - [2022-07-05 15:48:29,656] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:48:30 GMT'
    'ETag': '"0x8DA5EB6F4BA7239"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'c29ae4dd-d01e-00a0-0a9f-90cfa6000000'
    'x-ms-client-request-id': '0f5d877e-fc93-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:48:30 GMT'
[2022-07-05 15:48:29,662] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:48:29,671] {logging_mixin.py:115} INFO - [2022-07-05 15:48:29,670] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:48:29,685] {logging_mixin.py:115} INFO - [2022-07-05 15:48:29,685] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-01T00:00:00+00:00, run_after=2022-05-02T00:00:00+00:00
[2022-07-05 15:48:29,703] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.544 seconds
[2022-07-05 15:49:05,000] {processor.py:153} INFO - Started process (PID=10618) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:49:05,001] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:49:05,001] {logging_mixin.py:115} INFO - [2022-07-05 15:49:05,001] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:49:05,880] {logging_mixin.py:115} INFO - /tmp/tmpuotdaa7k/covid19.json
[2022-07-05 15:49:05,896] {logging_mixin.py:115} INFO - [2022-07-05 15:49:05,896] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:49:05,899] {logging_mixin.py:115} INFO - [2022-07-05 15:49:05,899] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A49%3A05.881074.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2662'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '255e8c30-fc93-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:49:06,734] {logging_mixin.py:115} INFO - [2022-07-05 15:49:06,734] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:49:07 GMT'
    'ETag': '"0x8DA5EB70AD1556C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2a3fb262-801e-003b-2d9f-900ea3000000'
    'x-ms-client-request-id': '255e8c30-fc93-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:49:07 GMT'
[2022-07-05 15:49:06,741] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:49:06,754] {logging_mixin.py:115} INFO - [2022-07-05 15:49:06,754] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:49:06,790] {logging_mixin.py:115} INFO - [2022-07-05 15:49:06,790] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-01T00:00:00+00:00, run_after=2022-05-02T00:00:00+00:00
[2022-07-05 15:49:06,810] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.813 seconds
[2022-07-05 15:50:44,153] {processor.py:153} INFO - Started process (PID=11755) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:50:44,156] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:50:44,157] {logging_mixin.py:115} INFO - [2022-07-05 15:50:44,157] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:50:45,055] {logging_mixin.py:115} INFO - /tmp/tmpzw26d1vc/covid19.json
[2022-07-05 15:50:45,067] {logging_mixin.py:115} INFO - [2022-07-05 15:50:45,067] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:50:45,070] {logging_mixin.py:115} INFO - [2022-07-05 15:50:45,070] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A50%3A45.055220.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '3209'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '607ad0a8-fc93-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:50:45,763] {logging_mixin.py:115} INFO - [2022-07-05 15:50:45,762] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:50:46 GMT'
    'ETag': '"0x8DA5EB745D06BE4"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '147beb8f-101e-0080-5ba0-90b401000000'
    'x-ms-client-request-id': '607ad0a8-fc93-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:50:46 GMT'
[2022-07-05 15:50:45,768] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:50:45,787] {logging_mixin.py:115} INFO - [2022-07-05 15:50:45,787] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:50:45,811] {logging_mixin.py:115} INFO - [2022-07-05 15:50:45,811] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-13T00:00:00+00:00, run_after=2022-05-14T00:00:00+00:00
[2022-07-05 15:50:45,832] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.681 seconds
[2022-07-05 15:51:18,543] {processor.py:153} INFO - Started process (PID=11828) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:51:18,548] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:51:18,548] {logging_mixin.py:115} INFO - [2022-07-05 15:51:18,548] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:51:19,466] {logging_mixin.py:115} INFO - /tmp/tmpxnm50k0j/covid19.json
[2022-07-05 15:51:19,480] {logging_mixin.py:115} INFO - [2022-07-05 15:51:19,480] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:51:19,488] {logging_mixin.py:115} INFO - [2022-07-05 15:51:19,488] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A51%3A19.467045.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2600'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '74fe9276-fc93-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:51:20,477] {logging_mixin.py:115} INFO - [2022-07-05 15:51:20,477] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:51:21 GMT'
    'ETag': '"0x8DA5EB75A7F061E"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '48b76d83-d01e-006b-3ba0-90ccf3000000'
    'x-ms-client-request-id': '74fe9276-fc93-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:51:21 GMT'
[2022-07-05 15:51:20,483] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:51:20,497] {logging_mixin.py:115} INFO - [2022-07-05 15:51:20,492] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:51:20,523] {logging_mixin.py:115} INFO - [2022-07-05 15:51:20,523] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-13T00:00:00+00:00, run_after=2022-05-14T00:00:00+00:00
[2022-07-05 15:51:20,539] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.998 seconds
[2022-07-05 15:51:55,890] {processor.py:153} INFO - Started process (PID=11898) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:51:55,890] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:51:55,891] {logging_mixin.py:115} INFO - [2022-07-05 15:51:55,891] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:51:56,919] {logging_mixin.py:115} INFO - /tmp/tmpd0kgfn5a/covid19.json
[2022-07-05 15:51:56,937] {logging_mixin.py:115} INFO - [2022-07-05 15:51:56,937] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:51:56,941] {logging_mixin.py:115} INFO - [2022-07-05 15:51:56,941] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A51%3A56.920299.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2453'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '8b51799e-fc93-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:51:57,643] {logging_mixin.py:115} INFO - [2022-07-05 15:51:57,642] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:51:58 GMT'
    'ETag': '"0x8DA5EB770A35A6C"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f25deea2-901e-0018-31a0-909460000000'
    'x-ms-client-request-id': '8b51799e-fc93-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:51:57 GMT'
[2022-07-05 15:51:57,649] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:51:57,662] {logging_mixin.py:115} INFO - [2022-07-05 15:51:57,662] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:51:57,692] {logging_mixin.py:115} INFO - [2022-07-05 15:51:57,692] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-13T00:00:00+00:00, run_after=2022-05-14T00:00:00+00:00
[2022-07-05 15:51:57,708] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.826 seconds
[2022-07-05 15:52:32,967] {processor.py:153} INFO - Started process (PID=11978) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:52:32,970] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:52:32,971] {logging_mixin.py:115} INFO - [2022-07-05 15:52:32,971] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:52:33,968] {logging_mixin.py:115} INFO - /tmp/tmp87kinm49/covid19.json
[2022-07-05 15:52:33,979] {logging_mixin.py:115} INFO - [2022-07-05 15:52:33,979] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:52:33,987] {logging_mixin.py:115} INFO - [2022-07-05 15:52:33,986] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A52%3A33.968866.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2846'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'a1662a9a-fc93-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:52:34,882] {logging_mixin.py:115} INFO - [2022-07-05 15:52:34,882] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:52:36 GMT'
    'ETag': '"0x8DA5EB786D2BCC8"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd37de0f1-601e-0041-69a0-9013e3000000'
    'x-ms-client-request-id': 'a1662a9a-fc93-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:52:35 GMT'
[2022-07-05 15:52:34,895] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:52:34,923] {logging_mixin.py:115} INFO - [2022-07-05 15:52:34,923] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:52:34,959] {logging_mixin.py:115} INFO - [2022-07-05 15:52:34,959] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-13T00:00:00+00:00, run_after=2022-05-14T00:00:00+00:00
[2022-07-05 15:52:34,993] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 2.028 seconds
[2022-07-05 15:53:11,048] {processor.py:153} INFO - Started process (PID=12080) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:53:11,049] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:53:11,049] {logging_mixin.py:115} INFO - [2022-07-05 15:53:11,049] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:53:11,939] {logging_mixin.py:115} INFO - /tmp/tmpmk8salsa/covid19.json
[2022-07-05 15:53:11,952] {logging_mixin.py:115} INFO - [2022-07-05 15:53:11,952] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:53:11,954] {logging_mixin.py:115} INFO - [2022-07-05 15:53:11,954] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A53%3A11.939433.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2544'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'b8078c80-fc93-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:53:12,667] {logging_mixin.py:115} INFO - [2022-07-05 15:53:12,667] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:53:13 GMT'
    'ETag': '"0x8DA5EB79D531C47"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '29e3ee5c-001e-0068-7aa0-902d97000000'
    'x-ms-client-request-id': 'b8078c80-fc93-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:53:13 GMT'
[2022-07-05 15:53:12,675] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:53:12,691] {logging_mixin.py:115} INFO - [2022-07-05 15:53:12,691] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:53:12,710] {logging_mixin.py:115} INFO - [2022-07-05 15:53:12,710] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-13T00:00:00+00:00, run_after=2022-05-14T00:00:00+00:00
[2022-07-05 15:53:12,726] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.685 seconds
[2022-07-05 15:53:52,633] {processor.py:153} INFO - Started process (PID=12288) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:53:52,634] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:53:52,635] {logging_mixin.py:115} INFO - [2022-07-05 15:53:52,635] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:53:53,593] {logging_mixin.py:115} INFO - /tmp/tmp5g3a9ng7/covid19.json
[2022-07-05 15:53:53,604] {logging_mixin.py:115} INFO - [2022-07-05 15:53:53,604] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:53:53,609] {logging_mixin.py:115} INFO - [2022-07-05 15:53:53,609] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A53%3A53.593324.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2899'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'd0db494a-fc93-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:53:54,307] {logging_mixin.py:115} INFO - [2022-07-05 15:53:54,307] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:53:55 GMT'
    'ETag': '"0x8DA5EB7B6245F58"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b78a5a0d-a01e-003c-63a0-9062c0000000'
    'x-ms-client-request-id': 'd0db494a-fc93-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:53:54 GMT'
[2022-07-05 15:53:54,313] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:53:54,329] {logging_mixin.py:115} INFO - [2022-07-05 15:53:54,328] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:53:54,358] {logging_mixin.py:115} INFO - [2022-07-05 15:53:54,358] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-14T00:00:00+00:00, run_after=2022-05-15T00:00:00+00:00
[2022-07-05 15:53:54,371] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.747 seconds
[2022-07-05 15:54:33,789] {processor.py:153} INFO - Started process (PID=12549) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:54:33,792] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:54:33,793] {logging_mixin.py:115} INFO - [2022-07-05 15:54:33,793] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:54:34,660] {logging_mixin.py:115} INFO - /tmp/tmpwit98x5b/covid19.json
[2022-07-05 15:54:34,670] {logging_mixin.py:115} INFO - [2022-07-05 15:54:34,670] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:54:34,676] {logging_mixin.py:115} INFO - [2022-07-05 15:54:34,676] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A54%3A34.660583.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '3244'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'e9560924-fc93-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:54:35,420] {logging_mixin.py:115} INFO - [2022-07-05 15:54:35,420] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:54:36 GMT'
    'ETag': '"0x8DA5EB7CEA238F0"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'd1b5c6a7-b01e-0099-3aa0-9034ba000000'
    'x-ms-client-request-id': 'e9560924-fc93-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:54:35 GMT'
[2022-07-05 15:54:35,430] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:54:35,441] {logging_mixin.py:115} INFO - [2022-07-05 15:54:35,441] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:54:35,469] {logging_mixin.py:115} INFO - [2022-07-05 15:54:35,469] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-16T00:00:00+00:00, run_after=2022-05-17T00:00:00+00:00
[2022-07-05 15:54:35,493] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.703 seconds
[2022-07-05 15:55:05,948] {processor.py:153} INFO - Started process (PID=12609) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:55:05,949] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:55:05,950] {logging_mixin.py:115} INFO - [2022-07-05 15:55:05,950] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:55:06,807] {logging_mixin.py:115} INFO - /tmp/tmpx37x6a9e/covid19.json
[2022-07-05 15:55:06,817] {logging_mixin.py:115} INFO - [2022-07-05 15:55:06,817] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:55:06,820] {logging_mixin.py:115} INFO - [2022-07-05 15:55:06,819] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A55%3A06.807679.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2753'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': 'fc7ea6aa-fc93-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:55:07,770] {logging_mixin.py:115} INFO - [2022-07-05 15:55:07,770] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:55:08 GMT'
    'ETag': '"0x8DA5EB7E1E85BEE"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '3b790938-e01e-005f-7da0-90ff3b000000'
    'x-ms-client-request-id': 'fc7ea6aa-fc93-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:55:08 GMT'
[2022-07-05 15:55:07,777] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:55:07,786] {logging_mixin.py:115} INFO - [2022-07-05 15:55:07,786] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:55:07,802] {logging_mixin.py:115} INFO - [2022-07-05 15:55:07,802] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-16T00:00:00+00:00, run_after=2022-05-17T00:00:00+00:00
[2022-07-05 15:55:07,832] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.886 seconds
[2022-07-05 15:55:39,953] {processor.py:153} INFO - Started process (PID=12678) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:55:39,957] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:55:39,957] {logging_mixin.py:115} INFO - [2022-07-05 15:55:39,957] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:55:40,914] {logging_mixin.py:115} INFO - /tmp/tmp1rnp_3mg/covid19.json
[2022-07-05 15:55:40,931] {logging_mixin.py:115} INFO - [2022-07-05 15:55:40,930] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:55:40,933] {logging_mixin.py:115} INFO - [2022-07-05 15:55:40,933] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A55%3A40.914755.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '3871'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '10d3e8ea-fc94-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:55:41,621] {logging_mixin.py:115} INFO - [2022-07-05 15:55:41,621] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:55:42 GMT'
    'ETag': '"0x8DA5EB7F6133532"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '841737e4-f01e-007c-54a0-9065f8000000'
    'x-ms-client-request-id': '10d3e8ea-fc94-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:55:42 GMT'
[2022-07-05 15:55:41,629] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:55:41,641] {logging_mixin.py:115} INFO - [2022-07-05 15:55:41,641] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:55:41,661] {logging_mixin.py:115} INFO - [2022-07-05 15:55:41,661] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-16T00:00:00+00:00, run_after=2022-05-17T00:00:00+00:00
[2022-07-05 15:55:41,678] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.728 seconds
[2022-07-05 15:56:17,311] {processor.py:153} INFO - Started process (PID=12748) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:56:17,311] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:56:17,312] {logging_mixin.py:115} INFO - [2022-07-05 15:56:17,312] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:56:18,127] {logging_mixin.py:115} INFO - /tmp/tmpnvjayphy/covid19.json
[2022-07-05 15:56:18,134] {logging_mixin.py:115} INFO - [2022-07-05 15:56:18,134] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:56:18,136] {logging_mixin.py:115} INFO - [2022-07-05 15:56:18,136] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A56%3A18.127244.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2874'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '2700b2e2-fc94-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:56:19,072] {logging_mixin.py:115} INFO - [2022-07-05 15:56:19,072] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:56:20 GMT'
    'ETag': '"0x8DA5EB80C62EBB7"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'bc3dcdff-901e-007a-44a0-905647000000'
    'x-ms-client-request-id': '2700b2e2-fc94-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:56:20 GMT'
[2022-07-05 15:56:19,078] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:56:19,091] {logging_mixin.py:115} INFO - [2022-07-05 15:56:19,091] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:56:19,110] {logging_mixin.py:115} INFO - [2022-07-05 15:56:19,110] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-16T00:00:00+00:00, run_after=2022-05-17T00:00:00+00:00
[2022-07-05 15:56:19,127] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.818 seconds
[2022-07-05 15:56:53,868] {processor.py:153} INFO - Started process (PID=12827) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:56:53,868] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:56:53,869] {logging_mixin.py:115} INFO - [2022-07-05 15:56:53,869] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:56:54,814] {logging_mixin.py:115} INFO - /tmp/tmpxq9uy9ey/covid19.json
[2022-07-05 15:56:54,823] {logging_mixin.py:115} INFO - [2022-07-05 15:56:54,822] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:56:54,826] {logging_mixin.py:115} INFO - [2022-07-05 15:56:54,826] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A56%3A54.814668.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '3212'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '3cdf02d0-fc94-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:56:55,539] {logging_mixin.py:115} INFO - [2022-07-05 15:56:55,539] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:56:56 GMT'
    'ETag': '"0x8DA5EB8221BCD81"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '9ad0d989-f01e-006c-58a0-90a090000000'
    'x-ms-client-request-id': '3cdf02d0-fc94-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:56:55 GMT'
[2022-07-05 15:56:55,544] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:56:55,554] {logging_mixin.py:115} INFO - [2022-07-05 15:56:55,554] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:56:55,572] {logging_mixin.py:115} INFO - [2022-07-05 15:56:55,572] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-16T00:00:00+00:00, run_after=2022-05-17T00:00:00+00:00
[2022-07-05 15:56:55,592] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.727 seconds
[2022-07-05 15:57:29,884] {processor.py:153} INFO - Started process (PID=12894) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:57:29,885] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:57:29,886] {logging_mixin.py:115} INFO - [2022-07-05 15:57:29,886] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:57:30,741] {logging_mixin.py:115} INFO - /tmp/tmpbwo_v5_x/covid19.json
[2022-07-05 15:57:30,748] {logging_mixin.py:115} INFO - [2022-07-05 15:57:30,748] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:57:30,753] {logging_mixin.py:115} INFO - [2022-07-05 15:57:30,753] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A57%3A30.742140.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2713'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '5249394c-fc94-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:57:31,578] {logging_mixin.py:115} INFO - [2022-07-05 15:57:31,578] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:57:32 GMT'
    'ETag': '"0x8DA5EB83794E7BB"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'dbe966e3-301e-0063-05a1-90d6fc000000'
    'x-ms-client-request-id': '5249394c-fc94-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:57:32 GMT'
[2022-07-05 15:57:31,583] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:57:31,596] {logging_mixin.py:115} INFO - [2022-07-05 15:57:31,596] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:57:31,615] {logging_mixin.py:115} INFO - [2022-07-05 15:57:31,615] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-16T00:00:00+00:00, run_after=2022-05-17T00:00:00+00:00
[2022-07-05 15:57:31,630] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.749 seconds
[2022-07-05 15:58:02,504] {processor.py:153} INFO - Started process (PID=12999) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:58:02,505] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:58:02,506] {logging_mixin.py:115} INFO - [2022-07-05 15:58:02,505] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:58:03,438] {logging_mixin.py:115} INFO - /tmp/tmpo86j8q1i/covid19.json
[2022-07-05 15:58:03,449] {logging_mixin.py:115} INFO - [2022-07-05 15:58:03,449] {base.py:68} INFO - Using connection ID 'wasbconn' for task execution.
[2022-07-05 15:58:03,451] {logging_mixin.py:115} INFO - [2022-07-05 15:58:03,451] {_universal.py:473} INFO - Request URL: 'https://serasadatalake.blob.core.windows.net/landingzone/covid19/2022/7/covid19_2022-07-05%2015%3A58%3A03.438408.json'
Request method: 'PUT'
Request headers:
    'x-ms-blob-type': 'REDACTED'
    'Content-Length': '2502'
    'If-None-Match': '*'
    'x-ms-version': 'REDACTED'
    'Content-Type': 'application/octet-stream'
    'Accept': 'application/xml'
    'User-Agent': 'azsdk-python-storage-blob/12.8.1 Python/3.10.4 (Linux-5.15.0-39-generic-x86_64-with-glibc2.35)'
    'x-ms-date': 'REDACTED'
    'x-ms-client-request-id': '65c66fbc-fc94-11ec-9005-b11393f1182e'
    'Authorization': 'REDACTED'
A body is sent with the request
[2022-07-05 15:58:04,239] {logging_mixin.py:115} INFO - [2022-07-05 15:58:04,239] {_universal.py:504} INFO - Response status: 201
Response headers:
    'Content-Length': '0'
    'Content-MD5': 'REDACTED'
    'Last-Modified': 'Tue, 05 Jul 2022 18:58:05 GMT'
    'ETag': '"0x8DA5EB84B0A3DC2"'
    'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '397147fc-d01e-0026-3da1-90031f000000'
    'x-ms-client-request-id': '65c66fbc-fc94-11ec-9005-b11393f1182e'
    'x-ms-version': 'REDACTED'
    'x-ms-content-crc64': 'REDACTED'
    'x-ms-request-server-encrypted': 'REDACTED'
    'Date': 'Tue, 05 Jul 2022 18:58:04 GMT'
[2022-07-05 15:58:04,248] {processor.py:651} INFO - DAG(s) dict_keys(['twitter_dag2']) retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:58:04,258] {logging_mixin.py:115} INFO - [2022-07-05 15:58:04,258] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-05 15:58:04,281] {logging_mixin.py:115} INFO - [2022-07-05 15:58:04,281] {dag.py:2927} INFO - Setting next_dagrun for twitter_dag2 to 2022-05-16T00:00:00+00:00, run_after=2022-05-17T00:00:00+00:00
[2022-07-05 15:58:04,298] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 1.796 seconds
[2022-07-05 15:58:37,646] {processor.py:153} INFO - Started process (PID=13134) to work on /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:58:37,649] {processor.py:641} INFO - Processing file /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py for tasks to queue
[2022-07-05 15:58:37,650] {logging_mixin.py:115} INFO - [2022-07-05 15:58:37,650] {dagbag.py:507} INFO - Filling up the DagBag from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:58:37,655] {logging_mixin.py:115} INFO - [2022-07-05 15:58:37,655] {dagbag.py:320} ERROR - Failed to import: /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
Traceback (most recent call last):
  File "/home/nicholas/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py", line 17
    'depends_on_past':False
                      
SyntaxError: invalid syntax. Perhaps you forgot a comma?
[2022-07-05 15:58:37,656] {processor.py:653} WARNING - No viable dags retrieved from /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py
[2022-07-05 15:58:37,678] {processor.py:161} INFO - Processing /home/nicholas/Desktop/Code/airflow/dags/minha_dag2.py took 0.035 seconds
